version: '3.8'

services:
  trading-bot:
    build: .
    container_name: solana-trading-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G 